### ISSUE TITLE
Suggestion for the next version

### ISSUE THREAD

**Issue by nicolascasadei** [qbicsoftware/metadata-doc#2]
Hi Marie, 

I was thinking to use this function to monitor changes that need to be implemented.

In the page Instructions, I would add in the point 3. Shipment:

- "Shipment should be planed at least 48 hours prior week-end or bank holidays to avoid long delivery time."
- "Inserting the printed metadata sheet within the samples transport box is important to allow a fast identification of the samples in our laboratories."

**Comment by qbicStefanC** [comment]
Hi
I would propose to update the email addresses in the second sheet to

"Please   send this form to: ncct-labor@med.uni-tuebingen.de and support@qbic.zendesk.com"

as the QBiC Team needs to review the metadata sheet in order to check if the most necessary info is given. Further we have to add the QBiC barcodes which are also necessary for the lab to start working on the samples (in case it is a QBiC project). In a next step we usually send this updated metadata sheet to the lab and the client. That would be then also conform with the suggested updates of Nicolas here.

Thanks
Stefan

**Comment by nicolascasadei** [comment]
In the page Samples, I would add in the "To be filled by the customer":

- a column called: "Analysis to be performed"
- as comment of this column: "Enter the service description as indicated on the quote for each samples, separate when applicable different services using semicolumn"

This will avoid possible confusion on the worflows.

**Comment by ghost** [comment]
Hi guys,

sorry for my late response, but there was some kind of problem with the notification settings, but I fixed it now.

> I was thinking to use this function to monitor changes that need to be implemented.

Yes, that is a good idea and we should stick to this format then, please also let your lab memebers know.

> In the page Instructions, I would add in the point 3. Shipment:
>     * "Shipment should be planed at least 48 hours prior week-end or bank holidays to avoid long delivery time."
>     * "Inserting the printed metadata sheet within the samples transport box is important to allow a fast identification of the samples in our laboratories."

I will include these changes in the new version.

----
> I would propose to update the email addresses in the second sheet to
> "Please send this form to: [ncct-labor@med.uni-tuebingen.de](mailto:ncct-labor@med.uni-tuebingen.de) and [support@qbic.zendesk.com](mailto:support@qbic.zendesk.com)"
> 
> as the QBiC Team needs to review the metadata sheet in order to check if the most necessary info is given. Further we have to add the QBiC barcodes which are also necessary for the lab to start working on the samples (in case it is a QBiC project). In a next step we usually send this updated metadata sheet to the lab and the client. That would be then also conform with the suggested updates of Nicolas here.

We used to have only the Zendesk mailing address included, but then the customers sometimes forgot to send it to the lab directly before/with the shipment. The labs asked me to make these changes and I did not see a problem, since we use Zendesk for the communication between the customer, the labs and QBiC. Hence, no metadata sheet should go under our radar, but of course, I can also add the Zendesk address, too.

----
> In the page Samples, I would add in the "To be filled by the customer":
>
>     * a column called: "Analysis to be performed"
>     * as comment of this column: "Enter the service description as indicated on the quote for each samples, separate when applicable different services using semicolumn"
> 
> This will avoid possible confusion on the workflows.

Could you please send an example on how this could look like, then I will include it in the next version. Since, I would like to add examplary pre-filled metadata sheets in order to make the customers understand better what we need.

Best,
Marie
